org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Fabric (cek di https://fabricmc.net/develop)
minecraft_version=26.3
loader_version=0.19.5
loom_version=1.17-SNAPSHOT

# Mod
version=1.0.0
group=com.chainmine
archives_base_name=chainmine

# Dependencies
fabric_api_version=0.162.0+26.3
